"resources"
{
"maps/dod_4e_anduze.res" "file"
"materials/models/surgeon/blitzdesert.vmt" "file"
"materials/models/surgeon/blitzdesert.vtf" "file"
"materials/models/surgeon/blitzgrey.vmt" "file"
"materials/models/surgeon/blitzgrey.vtf" "file"
"materials/models/surgeon/blitzwindows.vmt" "file"
"materials/models/surgeon/citroen.vmt" "file"
"materials/models/surgeon/citroen.vtf" "file"
"materials/models/surgeon/citroen_int.vmt" "file"
"materials/models/surgeon/citroen_int.vtf" "file"
"materials/models/surgeon/citroen_windows.vmt" "file"
"materials/models/surgeon/citroen_windows2.vmt" "file"
"materials/models/surgeon/citroen_windows2.vtf" "file"
"materials/models/surgeon/citroen_windows3.vmt" "file"
"materials/models/surgeon/citroen_windows3.vtf" "file"
"models/surgeon/citroen.dx80.vtx" "file"
"models/surgeon/citroen.dx90.vtx" "file"
"models/surgeon/citroen.mdl" "file"
"models/surgeon/citroen.phy" "file"
"models/surgeon/citroen.sw.vtx" "file"
"models/surgeon/citroen.vvd" "file"
"models/surgeon/opelblitz_a.dx80.vtx" "file"
"models/surgeon/opelblitz_a.dx90.vtx" "file"
"models/surgeon/opelblitz_a.mdl" "file"
"models/surgeon/opelblitz_a.phy" "file"
"models/surgeon/opelblitz_a.sw.vtx" "file"
"models/surgeon/opelblitz_a.vvd" "file"
}